name: coexistence
version: '0.1.0.0'
category: Web
author: Ignat Insarov
maintainer: kindaro@gmail.com
copyright: 2017 Ignat Insarov
license: ISC
github: kindaro/coexistence
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Data.Graph.Inductive.TotalOrder
  - Data.Graph.Inductive.Set
  - Data.Graph.Inductive.Event
  - Data.Stage
  dependencies:
  - base >=4.7 && <5
  - containers
  - fgl
  - set-monad
executables:
  coexistence-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - coexistence
    - containers
    - fgl
    - set-monad
# tests:
#   coexistence-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - base
#     - coexistence
